/**
 * ⚡ Vella Next-Generation Type Definitions
 * Auto-generated by Vella Backend Engine (Zero-Config Sync).
 * DO NOT EDIT MANUALLY - This file is automatically synchronized with your Rust backend.
 */

// ==========================================
// 1. Core Auth & System Types
// ==========================================

export type VellaRole = 'Admin' | 'Manager' | 'Editor' | 'Viewer';

export interface VellaUser {
  id: number;
  username: string;
  email: string;
  role: VellaRole;
  is_active: boolean;
  oauth_provider?: string | null;
}

export interface VellaSession {
  id: number;
  token: string;
  user_id: number;
  username: string;
  role: VellaRole;
  expires_at: string;
}

// ==========================================
// 2. Query & Vector Search Types
// ==========================================

export interface QueryOptions {
  limit?: number;
  offset?: number;
  order?: string;
  search?: string;
  filters?: Record<string, string | number | boolean>;
}

export interface PaginatedResult<T> {
  success: boolean;
  total: number;
  limit: number;
  offset: number;
  data: T[];
}

export type DistanceMetric = 'Cosine' | 'Euclidean' | 'DotProduct';

export interface VectorSearchQuery {
  model: string;
  vector_field?: string;
  query_vector: number[];
  top_k?: number;
  metric?: DistanceMetric;
}

export interface VectorSearchResult<T = any> {
  id: number;
  score: number;
  record: T;
}

// ==========================================
// 3. Realtime Sync Types
// ==========================================

export type RealtimeAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'ROLLBACK' | 'REQUEST' | 'RESOLVE';

export interface RealtimeEvent<T = any> {
  topic: string;
  event: RealtimeAction;
  payload: {
    model?: string;
    id?: number;
    data?: T;
    changes?: Partial<T>;
    log_id?: number;
    approval_id?: number;
    approved?: boolean;
  };
  timestamp: string;
}

// ==========================================
// 4. Domain Models
// ==========================================

/**
 * Model: Article (General)
 */
export interface Article {
  /** Primary Key */
  id: number;
  title: string;
  content?: string;
  /** Vector Embedding (1536 dimensions) */
  embedding?: number[];
  status?: 'Draft' | 'Published';
  /** Creation timestamp */
  created_at?: string;
  /** Last modification timestamp */
  updated_at?: string;
}

// ==========================================
// 5. Model Schema Registry Map
// ==========================================
export interface VellaModelMap {
  'article': Article;
  'articles': Article;
}
export type VellaModelName = keyof VellaModelMap;