use crate::model::field::{Field, FieldType};
use crate::model::schema::ModelSchema;
use crate::model::registry::SchemaRegistry;
use std::fs;
use std::path::Path;

pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    /// Generate TypeScript field type
    pub fn ts_field_type(field: &Field) -> String {
        match &field.field_type {
            FieldType::Integer | FieldType::Float | FieldType::Money { .. } | FieldType::ProgressBar { .. } | FieldType::ForeignKey { .. } => "number".to_string(),
            FieldType::Boolean => "boolean".to_string(),
            FieldType::DateTime => "string".to_string(), // ISO 8601 string
            FieldType::Enum { choices } => {
                let union: Vec<String> = choices.iter().map(|c| format!("'{}'", c)).collect();
                if union.is_empty() { "string".to_string() } else { union.join(" | ") }
            }
            FieldType::Json => "Record<string, any>".to_string(),
            FieldType::Vector { .. } => "number[]".to_string(),
            _ => "string".to_string(),
        }
    }

    /// Generate interface for a single model schema
    pub fn generate_model_interface(schema: &ModelSchema) -> String {
        let mut lines = Vec::new();
        lines.push(format!("/**"));
        lines.push(format!(" * Model: {} ({})", schema.name, schema.category));
        if let Some(ref desc) = schema.description {
            lines.push(format!(" * Description: {}", desc));
        }
        lines.push(format!(" */"));
        lines.push(format!("export interface {} {{", schema.name));

        for field in &schema.fields {
            let optional = if field.required || field.name == "id" { "" } else { "?" };
            let ts_type = Self::ts_field_type(field);
            if let Some(ref help) = field.help_text {
                lines.push(format!("  /** {} */", help));
            }
            lines.push(format!("  {}{}: {};", field.name, optional, ts_type));
        }

        lines.push("}".to_string());
        lines.join("\n")
    }

    /// Generate complete TypeScript declarations (.d.ts) for all registered schemas & system types
    pub fn generate_full_definitions(registry: &SchemaRegistry) -> String {
        let mut out = Vec::new();
        out.push(r#"/**
 * ⚡ Vella Next-Generation Type Definitions
 * Auto-generated by Vella Backend Engine (Zero-Config Sync).
 * DO NOT EDIT MANUALLY - This file is automatically synchronized with your Rust backend.
 */

// ==========================================
// 1. Core Auth & System Types
// ==========================================

export type VellaRole = 'Admin' | 'Manager' | 'Editor' | 'Viewer';

export interface VellaUser {
  id: number;
  username: string;
  email: string;
  role: VellaRole;
  is_active: boolean;
  oauth_provider?: string | null;
}

export interface VellaSession {
  id: number;
  token: string;
  user_id: number;
  username: string;
  role: VellaRole;
  expires_at: string;
}

// ==========================================
// 2. Query & Vector Search Types
// ==========================================

export interface QueryOptions {
  limit?: number;
  offset?: number;
  order?: string;
  search?: string;
  filters?: Record<string, string | number | boolean>;
}

export interface PaginatedResult<T> {
  success: boolean;
  total: number;
  limit: number;
  offset: number;
  data: T[];
}

export type DistanceMetric = 'Cosine' | 'Euclidean' | 'DotProduct';

export interface VectorSearchQuery {
  model: string;
  vector_field?: string;
  query_vector: number[];
  top_k?: number;
  metric?: DistanceMetric;
}

export interface VectorSearchResult<T = any> {
  id: number;
  score: number;
  record: T;
}

// ==========================================
// 3. Realtime Sync Types
// ==========================================

export type RealtimeAction = 'CREATE' | 'UPDATE' | 'DELETE' | 'ROLLBACK' | 'REQUEST' | 'RESOLVE';

export interface RealtimeEvent<T = any> {
  topic: string;
  event: RealtimeAction;
  payload: {
    model?: string;
    id?: number;
    data?: T;
    changes?: Partial<T>;
    log_id?: number;
    approval_id?: number;
    approved?: boolean;
  };
  timestamp: string;
}

// ==========================================
// 4. Domain Models
// ==========================================
"#.to_string());

        for schema in registry.all() {
            out.push(Self::generate_model_interface(schema));
            out.push(String::new());
        }

        // Schema Registry Map
        out.push("// ==========================================".to_string());
        out.push("// 5. Model Schema Registry Map".to_string());
        out.push("// ==========================================".to_string());
        out.push("export interface VellaModelMap {".to_string());
        for schema in registry.all() {
            out.push(format!("  '{}': {};", schema.name.to_lowercase(), schema.name));
            out.push(format!("  '{}': {};", schema.table_name, schema.name));
        }
        out.push("}".to_string());
        out.push("export type VellaModelName = keyof VellaModelMap;".to_string());

        out.join("\n")
    }

    /// Export TypeScript definitions to target path
    pub fn export_to_file(path: &str, registry: &SchemaRegistry) -> Result<(), std::io::Error> {
        let content = Self::generate_full_definitions(registry);
        if let Some(parent) = Path::new(path).parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(path, content)?;
        Ok(())
    }
}
