pub mod ipc;
pub mod config;
pub mod error;
pub mod events;
pub mod hooks;
pub mod resilience;
pub mod wasm;
pub mod chaos;
pub mod rtos;
pub mod tmr;
pub mod mesh;
pub mod local_first;

pub use config::VellaConfig;
pub use error::VellaError;
pub use events::{EventBus, SystemEvent};
pub use hooks::ModelHook;
pub use resilience::{CircuitBreaker, SystemWatchdog};
pub use rtos::RtosIsolator;
pub use tmr::TmrVoter;
pub use mesh::GossipMeshNode;
pub use local_first::LocalFirstSync;
