name: GitHub Pages (Rustdoc)

on:
  push:
    branches:
      - main

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Build Rustdocs
        run: cargo doc --no-deps --all-features
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          force_orphan: true
